### ISSUE TITLE
Set up initial directory structure for dicedb-cli

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dicedb-cli#1]
1. Set up the go project with the latest Golang SDK.
2. Use an existing library to set up a CLI, try exploring https://github.com/c-bata/go-prompt for the same.
3. Add support for basic RESP encoding/decoding for simple commands such as `SET`, `GET`, `DEL`.
4. Set up the README, with clear instructions on how to build the CLI from the source.
5. Set up unit tests for all the functionality being added.

**Comment by Dhroov7** [comment]
@JyotinderSingh Can you please assign this to me?
