### ISSUE TITLE
Consistency with redis : Show (type) in CLI output

### ISSUE THREAD

**Issue by shubzp** [DiceDB/dicedb-cli#10]
While working on [dice repo's issue # 809](https://github.com/DiceDB/dice/issues/809), I found that the type doesn't show up in dicedb-cli. 

The fix should be pretty straightforward. It's the printReply() that needs to be altered. This would make the CLI output consistent with redis.

**Comment by lucifercr07** [comment]
@shubzp thanks for reporting, will look into this.

**Comment by tarun-29** [comment]
can you assign me @lucifercr07

**Comment by JyotinderSingh** [comment]
@tarun-29 @shubzp sorry for the delayed response. Are either you still willing to pick up this issue?

**Comment by tarun-29** [comment]
Yes @JyotinderSingh i can work on this issue

**Comment by JyotinderSingh** [comment]
> Yes @JyotinderSingh i can work on this issue

Thanks, assigned!

**Comment by tarun-29** [comment]
i am delayed @JyotinderSingh but i am working on it will raise fix PR soon

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dicedb-cli/pull/20
