### ISSUE TITLE
When in watch mode, do not show any completer

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dicedb-cli#14]
Start the DiceDB server with `--enable-watch --enable-multithreading` and fix the following issue in DiceDB CLI.
Right now, we see completer when in `WATCH` mode, do not show that. For regular mode, it should be shown.

![image](https://github.com/user-attachments/assets/362bee9f-eb35-41ef-9206-f2f78df6ada6)

**Comment by vpsinghg** [comment]
@arpitbbhayani Can I pick this up ?

**Comment by raghavbabbar** [comment]
@arpitbbhayani  can I pick this

**Comment by vpsinghg** [comment]
@arpitbbhayani Is there any issue with the dicedb client's watchConn ? I am not receiving any messages in the `watchConn.Channel()`.

**Comment by arpitbbhayani** [comment]
https://github.com/DiceDB/dicedb-cli/pull/18
